name: Twitter WhatsApp Bot

on:
  schedule:
    - cron: "*/5 * * * *"  # Isso vai rodar o bot a cada 5 minutos, se necessário.
  push:
    branches:
      - main  # Para rodar também quando você fizer push na branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Faz o checkout do repositório

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Defina a versão do Python como 3.9 (mais estável)

    - name: Check Python version
      run: python --version  # Verifica se o Python está configurado corretamente

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Atualiza o pip
        pip install -r requirements.txt  # Instala todas as dependências do requirements.txt
        
        - name: Cache Python dependencies
  uses: actions/cache@v2
  with:
    path: ~/.cache/pip
    key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
    restore-keys: |
      ${{ runner.os }}-python-
      
      - name: Verificar dependências
  run: |
    pip show tweepy googletrans twilio


    - name: Run bot
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        TWITTER_USER: ${{ secrets.TWITTER_USER }}
        TWILIO_SID: ${{ secrets.TWILIO_SID }}
        TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
        TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
        TWILIO_TO: ${{ secrets.TWILIO_TO }}
      run: |
        python twitter_whatsapp_bot.py 

